[build]
  command = "npm run build"
  publish = "dist"
 [[redirects]]
  from = "/*"
  to = "/js/index.js"
  status = 200
[build.environment]
API_KEY = "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"
