[build]
  command = "npm run build"
  functions = "netlify-functions" [[redirects]]
  from = "/*"
  to = "/js/index.js"
  status = 200
[build.environment]
IP_KEY = "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"
